postgres_server_cert: |
 -----BEGIN CERTIFICATE-----
 MIIFnTCCA4WgAwIBAgIJAMQ4T7uP1QkFMA0GCSqGSIb3DQEBCwUAMGUxCzAJBgNV
 BAYTAlVTMRAwDgYDVQQIDAdGbG9yaWRhMQwwCgYDVQQHDANXUEMxHDAaBgNVBAoM
 E0RlZmF1bHQgQ29tcGFueSBMdGQxGDAWBgNVBAMMD2YwNGJtbS1kYm1vZG4wMTAe
 Fw0xOTA5MzAxOTUzNTZaFw0yMjA5MjkxOTUzNTZaMGUxCzAJBgNVBAYTAlVTMRAw
 DgYDVQQIDAdGbG9yaWRhMQwwCgYDVQQHDANXUEMxHDAaBgNVBAoME0RlZmF1bHQg
 Q29tcGFueSBMdGQxGDAWBgNVBAMMD2YwNGJtbS1kYm1vZG4wMTCCAiIwDQYJKoZI
 hvcNAQEBBQADggIPADCCAgoCggIBALKYLRqlXhc8v2ILzOxxaxf4zDBwi+lAv+Ye
 jRHVGSg2J90i8LsAMEUlyyy0C/NCLWamVVSQplFtRYm6PCnbaIKBf8N/9Xlq78l3
 VwOgbQX46ml7YDNxsv6ObLGwxRj8Y5j+6xEfDIyGLJE4ptYL2eOvAbVV+p6lq/7f
 9YzI8672r2efAbAxqpIm0XG0NuMj3wTauBO8L/fDI1VLuEib9e0YqgCEpo88aAaY
 L1ZPQKnEJansA0GQN+Yym5EHEptWqFIVu5CcIbRW9nTx3jWH4o9dPbNI2KlkVGm8
 4QgYxoWSp4NWPWBFjucviiawHg8lpTj06OtRnSMk/slVyXdtxkp5ofTt4qQrJ4eR
 6FauHU4+ms/7SFBJkejK7+OhO1Mq/zzjac/2HldgBFomu+ETS8Uy22R9M0CEMTHZ
 TJZKpeglZm2YmPhgqa4UavQ/2iXbHveQUnx2LTB4sFVr/JEQV5NxCbMt/0WXaUWi
 4z8dvVbR0SUVtiAN3PsHWXGXIDLfsGKLILhegv5bm+M/nJmtmfrDfhMvVjK9SyUn
 dNNbh6xlZBf08BUju0diX+2vQtvtw77ptnuQCeXbAOqOaD+6FaHDGQBAWHd8fC6s
 gKaeDjTpQNNLSHp/XsLnzNeGdGFwRUXrJrKwsxGeTj726nmNqR3rgkRcx5HFtxvP
 u1X5Ph2hAgMBAAGjUDBOMB0GA1UdDgQWBBSR5Ac8xJGxsPCt0musL9CL07wxuzAf
 BgNVHSMEGDAWgBSR5Ac8xJGxsPCt0musL9CL07wxuzAMBgNVHRMEBTADAQH/MA0G
 CSqGSIb3DQEBCwUAA4ICAQCKmjTaLGu02CsiwIh43dal+l3CBTJewGdhHUzdnDdm
 2EOskNkQed8IlxtnvolaMLvPKJTg2yrgH7O8KjnuYOrwT5xDckUw/30CDPLzDmDC
 yKuwNpMDw+JvKmCyJwdAhEh3NHLWcWpfd3xyvL7GAhx8PgXMbvExgc/I5XXdbd2R
 /+JyU+xSQ/9YClfyfQkJqX/CdGM5ceEObFEcSTux31UrmREANqdOB8xKIXAMoWhx
 1H0daEkLV4LzbzAIlux82fd58S9cochJoc/pF7YHfKix3prtB5RmUgaM+6K/uLOF
 vPaK59Qv5M3WgDQgVJAxz+pOLOAB95C5jwxFLXq78IrGsniQmgMRJO5s2SU0NO5+
 ECmdU08QHQ6636tzmt+f/omi8npuwNSIGYUpKFp/xiv4egbtXbBEkp1eED68tVQ6
 rJb2oDAfcfUwSBoK4+uNEhaMjgT6l75ko2kY3jC6abnRrA/OFGgL5vpLfV9t+StL
 U8J2vLw+xQ0Jzy7qU1goB0w4SyYE4/4t4aMrocNqWRUPOdrrWK9qHbXoeNMEXXU3
 GYUdEr9IoGRWftWfh+QXW+27/T0Mh0d33Yytc6LAcyS3ZGmSwkYU27HTSl8dCx26
 5Kx3IEwzqBs0J1SPnCwEKM+6jjvC1Sue/qpkQN/YulqydEZVHHTDLyc9iYadHjgm
 Ng==
 -----END CERTIFICATE-----
